[tool.poetry]
name = "wol"
version = "0.1.0"
description = ""
authors = ["Tim <jlemyp96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
wakeonlan = "^1.1"
pyexpect = "^1.0"
flask = "^1.1.2"
fabric = { version = "^2.5", markers = "platform_machine != 'mips'" } # не смог собрать pynacl
singledispatchmethod = { version = "^1.0", python = "~3.7.0" }
marshmallow = "^3.5.2"
validators = "^0.14.3"
scapy = "^2.4.3"

[tool.poetry.dev-dependencies]
ipython = "^7.5"
pytest = "^3.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
