name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install poetry
      - run: poetry build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          username: JleMyP
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile.prod
          registry: ghcr.io
          name: JleMyP/wol
          tag_names: true
          cache: true
      - uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          username: JleMyP
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile.prod
          registry: docker.pkg.github.com
          name: JleMyP/wol/wol
          tag_names: true
          cache: true
